import React, { useMemo, useState } from 'react';
import {
  Zap, Users, Home, Thermometer, Shield,
  TrendingUp, AlertTriangle, MapPin, DollarSign,
  Activity, Layers,
  MapPin as MapPinIcon, ArrowUpRight, BarChart3,
  ChevronRight, ChevronUp, ChevronDown,
  Clock, Sun, CloudSnow,
} from 'lucide-react';
import { useApp, isStale } from '../context';
import type { IntelIconKey, IntelLens, IntelItem } from '../intelligence';
import { buildIntelligence } from '../intelligence';
import { advisoriesFor } from '../advisories';
import type { AdvisoryUrgency } from '../advisories';
import { URGENCY_COLOR } from '../advisories';
import { scoreFor, rampColor, rampLabel, formatPct } from '../utils';

/**
 * Intelligence — always-on right sidebar.
 *
 * Content is fully lens-aware: operators, municipalities, and community
 * organisations each receive proactive intelligence relevant only to them.
 * Items are generated by the deterministic intelligence engine in
 * intelligence.ts — no hardcoded content.
 */

/* ─── Elapsed time helper ────────────────────────────────────── */
function elapsedSeconds(lastSuccess: Date | null): string {
  if (!lastSuccess) return '—';
  return `${Math.round((Date.now() - lastSuccess.getTime()) / 1000)}s ago`;
}

/* ─── Icon resolver ─────────────────────────────────────────── */
function IntelIcon({ k, size = 15, color }: { k: IntelIconKey; size?: number; color: string }) {
  const props = { size, style: { color, flexShrink: 0 } as React.CSSProperties };
  switch (k) {
    case 'zap':            return <Zap {...props} />;
    case 'users':          return <Users {...props} />;
    case 'home':           return <Home {...props} />;
    case 'thermometer':    return <Thermometer {...props} />;
    case 'shield':         return <Shield {...props} />;
    case 'trending-up':    return <TrendingUp {...props} />;
    case 'alert-triangle': return <AlertTriangle {...props} />;
    case 'map-pin':        return <MapPin {...props} />;
    case 'dollar-sign':    return <DollarSign {...props} />;
    case 'activity':       return <Activity {...props} />;
    case 'layers':         return <Layers {...props} />;
    default:               return <AlertTriangle {...props} />;
  }
}

/* ─── Advisory icon — keyword derived ─────────────────────── */
function AdvisoryIcon({ headline, urgency }: { headline: string; urgency: AdvisoryUrgency }) {
  const h = headline.toLowerCase();
  const color = URGENCY_COLOR[urgency];
  const p = { size: 15, style: { color, flexShrink: 0 } as React.CSSProperties };
  if (h.includes('heat') || h.includes('cool') || h.includes('shelter')) return <Sun {...p} />;
  if (h.includes('power') || h.includes('outage') || h.includes('energy')) return <Zap {...p} />;
  if (h.includes('ice') || h.includes('snow') || h.includes('freez')) return <CloudSnow {...p} />;
  return <AlertTriangle {...p} />;
}

/* ─── Urgency colour tokens ─────────────────────────────────── */
const URG_COLOR: Record<'critical' | 'elevated' | 'routine', string> = {
  critical: 'var(--alert)',
  elevated: 'var(--alert-mid)',
  routine:  'var(--ink-3)',
};

/* ─── Feed status dot ─────────────────────────────────────────── */
function StatusDot({ ok, warn }: { ok: boolean; warn: boolean }) {
  const bg = !ok ? 'var(--alert)' : warn ? 'var(--warning)' : 'var(--positive)';
  return (
    <span
      style={{ width: 6, height: 6, borderRadius: '50%', background: bg, flexShrink: 0, display: 'inline-block' }}
      aria-hidden
    />
  );
}

/* ─── Section divider header ─────────────────────────────────── */
function SectionHeader({ label, right }: { label: string; right?: React.ReactNode }) {
  return (
    <div className="px-4 pt-4 pb-2 flex items-center justify-between">
      <span className="text-[10px] uppercase tracking-[0.2em]" style={{ color: 'var(--ink-3)' }}>
        {label}
      </span>
      {right}
    </div>
  );
}

/* ─── Intelligence item card ─────────────────────────────────── */
function IntelCard({ item }: { item: IntelItem }) {
  const [expanded, setExpanded] = useState(false);
  const urgColor = URG_COLOR[item.urgency];
  return (
    <div className="border-b border-hairline">
      <button
        onClick={() => setExpanded(v => !v)}
        className="w-full text-left px-4 py-3 hover:bg-surface-2/60 transition-colors cursor-pointer"
        style={{ background: 'none', border: 'none' }}
      >
        <div className="flex items-start gap-2.5">
          <IntelIcon k={item.icon} color={urgColor} />
          <div className="flex-1 min-w-0">
            {/* Category pill */}
            <div className="text-[9px] uppercase tracking-[0.14em] mb-1" style={{ color: urgColor }}>
              {item.category}
            </div>
            {/* Headline */}
            <div className="text-[12px] font-medium leading-snug" style={{ color: 'var(--ink)' }}>
              {item.headline}
            </div>
            {/* Metric chip */}
            {item.metric && !expanded && (
              <div className="text-[10px] mt-1.5 tabular" style={{ color: 'var(--ink-3)' }}>
                <span style={{ color: 'var(--ink-4)' }}>{item.metric.label} · </span>
                {item.metric.value}
              </div>
            )}
          </div>
          <span style={{ color: 'var(--ink-4)', flexShrink: 0, marginTop: 2 }}>
            {expanded ? <ChevronUp size={12} /> : <ChevronDown size={12} />}
          </span>
        </div>
      </button>

      {expanded && (
        <div className="px-4 pb-3">
          {/* Detail */}
          <p className="text-[11px] leading-relaxed" style={{ color: 'var(--ink-3)' }}>
            {item.detail}
          </p>
          {/* Metric */}
          {item.metric && (
            <div
              className="mt-2 px-2.5 py-1.5 flex items-baseline justify-between"
              style={{ background: `${urgColor}0D`, borderRadius: 4 }}
            >
              <span className="text-[10px] uppercase tracking-[0.1em]" style={{ color: urgColor }}>
                {item.metric.label}
              </span>
              <span className="text-[13px] font-medium tabular" style={{ color: 'var(--ink)' }}>
                {item.metric.value}
              </span>
            </div>
          )}
          {/* Affected tracts */}
          {item.affectedTracts && item.affectedTracts.length > 0 && (
            <div className="mt-2 flex flex-wrap gap-1">
              {item.affectedTracts.slice(0, 4).map(n => (
                <span
                  key={n}
                  className="text-[10px] px-1.5 py-0.5 border border-hairline"
                  style={{ color: 'var(--ink-3)', borderRadius: 2 }}
                >
                  {n}
                </span>
              ))}
              {item.affectedTracts.length > 4 && (
                <span className="text-[10px] px-1.5 py-0.5" style={{ color: 'var(--ink-4)' }}>
                  +{item.affectedTracts.length - 4} more
                </span>
              )}
            </div>
          )}
          {/* Recommended action */}
          <div
            className="mt-3 pt-2.5 border-t border-hairline flex items-start gap-2"
          >
            <span className="text-[9px] uppercase tracking-[0.14em] shrink-0 mt-0.5" style={{ color: urgColor }}>
              Action
            </span>
            <span className="text-[11px] leading-snug" style={{ color: 'var(--ink-2)' }}>
              {item.action}
            </span>
          </div>
        </div>
      )}
    </div>
  );
}

/* ─── Lens labels + descriptors ─────────────────────────────── */
const LENS_HEADER: Record<IntelLens, { title: string; subtitle: string }> = {
  operator:  { title: 'Utility Intelligence', subtitle: 'Alectra Utilities · Operator view' },
  municipal: { title: 'Municipal Intelligence', subtitle: 'City of Brampton · Operational view' },
  community: { title: 'Community Intelligence', subtitle: 'Community organisations · Outreach view' },
};

/* ─── Main component ─────────────────────────────────────────── */
export default function IntelligencePanel() {
  const {
    tracts, lens, feeds, rollupByTract, citywideCounts,
    scenario, finance, percentiles, forecastPoints, selected,
  } = useApp();

  const [advisoriesOpen, setAdvisoriesOpen] = useState(true);

  /* Build lens-filtered intelligence items */
  const allItems = useMemo(
    () => buildIntelligence(tracts, percentiles, rollupByTract, scenario, finance, forecastPoints),
    [tracts, percentiles, rollupByTract, scenario, finance, forecastPoints],
  );

  const lensItems = useMemo(
    () => allItems.filter(item => item.lens.includes(lens as IntelLens)),
    [allItems, lens],
  );

  /* When a tract is selected: show its advisories; otherwise city-wide */
  const tractAdvisories = useMemo(
    () => selected ? advisoriesFor(selected, scenario, finance) : [],
    [selected, scenario, finance],
  );

  const cityAdvisories = useMemo(() => {
    if (selected) return null; // use tractAdvisories instead
    const rows: { headline: string; urgency: AdvisoryUrgency; detail: string; timeframe: string }[] = [];
    const seen = new Set<string>();
    for (const tract of tracts) {
      for (const adv of advisoriesFor(tract, scenario, finance)) {
        if (seen.has(adv.headline)) continue;
        seen.add(adv.headline);
        rows.push({ headline: adv.headline, urgency: adv.urgency, detail: adv.detail, timeframe: adv.timeframe });
      }
    }
    const order: Record<AdvisoryUrgency, number> = { critical: 0, elevated: 1, routine: 2 };
    return rows.sort((a, b) => order[a.urgency] - order[b.urgency]).slice(0, 6);
  }, [selected, tracts, scenario, finance]);

  /* Neighbourhood-focused intelligence: items that mention the selected tract */
  const focusedItems = useMemo(() => {
    if (!selected) return lensItems;
    const name = selected.neighbourhood;
    const matching = lensItems.filter(i => i.affectedTracts?.includes(name));
    return matching.length > 0 ? matching : lensItems;
  }, [lensItems, selected]);

  const totalActive = selected
    ? tractAdvisories.length
    : citywideCounts.critical + citywideCounts.elevated + citywideCounts.routine;

  /* Neighbourhood summary stats */
  const tractScore = selected ? scoreFor(selected, scenario) : null;
  const tractPct   = selected ? (percentiles.get(selected.ctuid) ?? 0) : null;
  const tractLabel = tractPct !== null ? rampLabel(tractPct) : null;
  const tractColor = tractPct !== null ? rampColor(tractPct) : null;

  /* Feed health */
  const weatherOk   = !feeds.weather.error;
  const weatherWarn = isStale(feeds.weather);
  const outageOk    = !feeds.outages.error;
  const outageWarn  = isStale(feeds.outages);
  const modelOk     = !feeds.communities.error;
  const modelWarn   = isStale(feeds.communities);

  if (lens === 'resident') return null;

  const lensKey = lens as IntelLens;
  const header  = LENS_HEADER[lensKey];
  const criticalCount = focusedItems.filter(i => i.urgency === 'critical').length;
  const elevatedCount = focusedItems.filter(i => i.urgency === 'elevated').length;

  const advisoryList = selected ? tractAdvisories : (cityAdvisories ?? []);

  return (
    <aside
      className="flex flex-col overflow-hidden"
      style={{
        flexShrink: 0,
        width: 288,
        margin: '10px 10px 10px 10px',
        background: '#ffffff',
        borderRadius: 8,
        border: '0.5px solid var(--hairline)',
        boxShadow: '0 4px 20px rgba(15,23,42,0.10)',
      }}
      aria-label="Preparedness intelligence"
    >
      {/* ── Panel header ───────────────────────────────────── */}
      <div className="px-4 pt-3 pb-3 border-b border-hairline flex-shrink-0">
        <div className="text-[11px] font-medium" style={{ color: 'var(--ink)' }}>{header.title}</div>
        <div className="text-[10px] mt-0.5" style={{ color: 'var(--ink-3)' }}>
          {selected ? selected.neighbourhood : header.subtitle}
        </div>
        {(criticalCount > 0 || elevatedCount > 0) && (
          <div className="flex items-center gap-2 mt-2">
            {criticalCount > 0 && (
              <span
                className="text-[9px] uppercase tracking-[0.12em] px-1.5 py-0.5"
                style={{ color: 'var(--alert)', background: 'rgba(154,52,18,0.07)', borderRadius: 3 }}
              >
                {criticalCount} critical
              </span>
            )}
            {elevatedCount > 0 && (
              <span
                className="text-[9px] uppercase tracking-[0.12em] px-1.5 py-0.5"
                style={{ color: 'var(--alert-mid)', background: 'rgba(194,65,12,0.07)', borderRadius: 3 }}
              >
                {elevatedCount} elevated
              </span>
            )}
          </div>
        )}
      </div>

      {/* ── Neighbourhood focus strip ─────────────────────── */}
      {selected && tractScore !== null && tractColor && tractLabel && (
        <div
          className="px-4 py-2.5 border-b border-hairline flex items-center justify-between flex-shrink-0"
          style={{ background: `${tractColor}0A` }}
        >
          <div>
            <div className="text-[9px] uppercase tracking-[0.14em]" style={{ color: 'var(--ink-3)' }}>
              Neighbourhood focus
            </div>
            <div className="text-[11px] mt-0.5" style={{ color: 'var(--ink-2)' }}>
              {formatPct(selected.pct_renters)} renters · {selected.population.toLocaleString()} pop
            </div>
          </div>
          <div className="text-right">
            <div className="text-[20px] font-medium tabular leading-none" style={{ color: tractColor }}>
              {tractScore.toFixed(0)}
            </div>
            <div
              className="text-[9px] uppercase tracking-[0.1em] mt-0.5 px-1.5 py-0.5"
              style={{ color: tractColor, background: `${tractColor}18`, borderRadius: 3 }}
            >
              {tractLabel}
            </div>
          </div>
        </div>
      )}

      <div className="flex-1 overflow-y-auto min-h-0">

        {/* ── 1. Proactive Intelligence Items ──────────────── */}
        {focusedItems.length === 0 ? (
          <div className="px-4 py-4 text-[12px] border-b border-hairline" style={{ color: 'var(--ink-3)' }}>
            No active intelligence items for this lens. Conditions within normal operational parameters.
          </div>
        ) : (
          focusedItems.map(item => <IntelCard key={item.id} item={item} />)
        )}

        {/* ── 2. Active Advisories (collapsible) ───────────── */}
        <SectionHeader
          label={selected ? 'Neighbourhood advisories' : 'Active advisories'}
          right={
            <div className="flex items-center gap-2">
              {totalActive > 0 && (
                <span
                  className="text-[10px] uppercase tracking-[0.1em] px-2 py-0.5"
                  style={{ borderRadius: 4, color: 'var(--alert)', background: 'rgba(154,52,18,0.07)' }}
                >
                  {totalActive}
                </span>
              )}
              <button
                onClick={() => setAdvisoriesOpen(v => !v)}
                className="cursor-pointer"
                style={{ color: 'var(--ink-4)', background: 'none', border: 'none', padding: 0, lineHeight: 1 }}
              >
                {advisoriesOpen ? <ChevronUp size={14} /> : <ChevronDown size={14} />}
              </button>
            </div>
          }
        />

        {advisoriesOpen && (
          advisoryList.length === 0 ? (
            <div className="px-4 py-3 text-[12px] border-b border-hairline" style={{ color: 'var(--ink-3)' }}>
              {selected ? 'No advisories for this neighbourhood. Standing readiness.' : 'No active advisories. Standing readiness.'}
            </div>
          ) : (
            advisoryList.map((adv, i) => (
              <div
                key={i}
                className="px-4 py-3 border-b border-hairline cursor-pointer hover:bg-surface-2/60 transition-colors"
              >
                <div className="flex items-start gap-2.5">
                  <AdvisoryIcon headline={adv.headline} urgency={adv.urgency} />
                  <div className="flex-1 min-w-0">
                    <div className="text-[12px] font-medium leading-snug" style={{ color: 'var(--ink)' }}>
                      {adv.headline}
                    </div>
                    {adv.detail && (
                      <div className="text-[11px] mt-1 leading-snug" style={{ color: 'var(--ink-3)' }}>
                        {adv.detail}
                      </div>
                    )}
                    {adv.timeframe && (
                      <div className="text-[10px] mt-1.5 uppercase tracking-[0.08em]" style={{ color: 'var(--ink-4)' }}>
                        {adv.timeframe}
                      </div>
                    )}
                  </div>
                  <ChevronRight size={12} style={{ color: 'var(--ink-4)', flexShrink: 0, marginTop: 2 }} />
                </div>
              </div>
            ))
          )
        )}

        {/* ── 3. Intervention Tools ────────────────────────── */}
        <SectionHeader label="Intervention tools" />

        {[
          { icon: <MapPinIcon size={13} style={{ color: 'var(--ink-3)', flexShrink: 0 }} />, title: 'Deploy temporary cooling site', sub: 'Simulate impact and coverage' },
          { icon: <ArrowUpRight size={13} style={{ color: 'var(--ink-3)', flexShrink: 0 }} />, title: 'Priority restoration planning', sub: 'Optimize restoration sequence' },
          { icon: <BarChart3 size={13} style={{ color: 'var(--ink-3)', flexShrink: 0 }} />, title: 'Resilience scenario modeling', sub: 'Compare intervention outcomes' },
        ].map(tool => (
          <button
            key={tool.title}
            className="w-full text-left px-4 py-3 border-b border-hairline hover:bg-surface-2/60 transition-colors cursor-pointer flex items-start gap-2.5"
            style={{ background: 'none' }}
          >
            {tool.icon}
            <div className="flex-1 min-w-0">
              <div className="text-[12px] font-medium" style={{ color: 'var(--ink)' }}>{tool.title}</div>
              <div className="text-[10px] mt-0.5" style={{ color: 'var(--ink-3)' }}>{tool.sub}</div>
            </div>
            <ChevronRight size={12} style={{ color: 'var(--ink-4)', flexShrink: 0, marginTop: 3 }} />
          </button>
        ))}

        <div className="px-4 py-2 border-b border-hairline">
          <button className="text-[10px] uppercase tracking-[0.1em] cursor-pointer hover:text-ink transition-colors" style={{ color: 'var(--ink-3)', background: 'none', border: 'none', padding: 0 }}>
            View all tools
          </button>
        </div>

        {/* ── 4. System Status ─────────────────────────────── */}
        <SectionHeader label="System status" />

        {[
          { label: 'Outage feed',         ok: outageOk,  warn: outageWarn,  lastSuccess: feeds.outages.lastSuccess },
          { label: 'Weather feed',        ok: weatherOk, warn: weatherWarn, lastSuccess: feeds.weather.lastSuccess },
          { label: 'Model recalculation', ok: modelOk,   warn: modelWarn,   lastSuccess: feeds.communities.lastSuccess },
        ].map(row => (
          <div key={row.label} className="px-4 py-2 border-b border-hairline flex items-center gap-2.5">
            <StatusDot ok={row.ok} warn={row.warn} />
            <span className="text-[12px] flex-1" style={{ color: 'var(--ink-2)' }}>{row.label}</span>
            <span className="text-[11px] flex items-center gap-1" style={{ color: 'var(--ink-3)' }}>
              {row.ok && !row.warn
                ? <><span style={{ color: 'var(--positive)' }}>Active</span> <Clock size={9} style={{ display: 'inline' }} /> {elapsedSeconds(row.lastSuccess)}</>
                : row.warn
                  ? <span style={{ color: 'var(--warning)' }}>Stale · {elapsedSeconds(row.lastSuccess)}</span>
                  : <span style={{ color: 'var(--alert)' }}>Error</span>
              }
            </span>
          </div>
        ))}

        {/* ── 5. Data Sources ──────────────────────────────── */}
        <div className="px-4 pt-4 pb-2 flex items-center justify-between">
          <span className="text-[10px] uppercase tracking-[0.2em]" style={{ color: 'var(--ink-3)' }}>Data sources</span>
          <button className="text-[10px] uppercase tracking-[0.1em] cursor-pointer hover:text-ink transition-colors" style={{ color: 'var(--ink-3)', background: 'none', border: 'none', padding: 0 }}>
            View all
          </button>
        </div>
        <div className="px-4 pb-6">
          {['Statistics Canada (2021)', 'Alectra Utilities', 'Open-Meteo', 'Ontario Energy Board', 'Bank of Canada'].map(src => (
            <div key={src} className="text-[11px] py-0.5 leading-loose" style={{ color: 'var(--ink-3)' }}>{src}</div>
          ))}
          <div className="text-[11px] mt-0.5" style={{ color: 'var(--ink-4)' }}>+3 more</div>
        </div>
      </div>
    </aside>
  );
}
